Add validation checking to client-side commit-msg

diff --git a/client-side-hooks/src/main/bash/commit-msg b/client-side-hooks/src/main/bash/commit-msg
--- a/client-side-hooks/src/main/bash/commit-msg
+++ b/client-side-hooks/src/main/bash/commit-msg
@@ -73,6 +73,9 @@
 #  - bash
 #  - sed
 #  - jq
+#  - cat
+#  - tail
+#  - head
 
 
 ######################################################
@@ -308,10 +311,172 @@ sed -i -e :a -e '/^\n*$/{$d;N;ba' -e '}' "$1"
 ######################################################
 # Validate commit message
 
-#todo
+# Check if the file is empty; a file containing newlines and/or white space only is considered empty
+if [ -z "$(cat "${1}")" ]; then
+	display_error "Commit message cannot be empty." "$1"
+	exit 1
+fi
+
+# fail if tab characters are used
+	# used literal tab character here in regex by using ctrl-v then tab
+	# do after all comments removed, since those are being removed because not sent anyway
+		# note that commit comments automatically added by commit contain tabs
+lineNum=$(sed -n '/	/=' "$1")
+if [ -n "$lineNum" ]; then
+	display_error "Commit message must not contain tabs, but tab found on line # $lineNum." "$1" "$lineNum"
+	exit 1
+fi
 
 
+# eval first line
+while IFS= read -r line
+do
 
-display_error "Always error out for testing" $1
+	# Check that hte first line is non-empty.  This is in compliance with thef ormat, and will be prevent script errors if the git message is aborted.
+	if [[ -z "$line" ]]; then
+		display_error 'First line cannot be empty'
+		exit 1
+	fi
+
+	# check that the first line has at least min chars
+	if is_string_min_char_compliant "$line" "$firstLineLengthMin"; then
+
+		# check that the first line doesn't exceed max chars
+		if is_string_max_char_compliant "$line" "$firstLineLengthMax"; then
+
+			# regex for:  type (required), scope (optional), and exclamation mark (optional).  1 or more characters necessary for type and scope, but otherwise doesn't check number of characters
+			regexp="^([a-zA-Z]+)(\(([a-zA-Z0-9]+)\))?([\!])?: [a-z]"
+
+			if [[ $line =~ $regexp ]]; then
+				theType=${BASH_REMATCH[1]}
+				scope=${BASH_REMATCH[3]}
+			else
+				theType=''
+				scope=''
+			fi
+			# if needed later, the exclamation mark can be captured with ${BASH_REMATCH[4]}
+
+			# type must be found from regex
+			if [ -z "$theType" ]; then
+				display_error "Bad forma of title line.  Could not determine 'type'." "$1" 1
+				exit 1
+			fi
+
+			# type must be a type defined in config file
+			typeFound='no'
+			for value in "${types[@]}"
+			do
+				if [[ "$theType" = "$value" ]]; then
+					typeFound='yes'
+					break
+				fi
+			done
+
+			# error if type wasn't defined in config file
+			if [[ ! "$typeFound" = "yes" ]]; then
+				display_error "Type '$theType' is not a valid type per configuration file '$config'." "$1" 1
+				exit 1
+			fi
+
+			# if the scope is found from the regex
+			if [ -n "$scope" ]; then
+
+				# scope must be defined in the config file
+				scopeFound='no'
+				for value in "${scopes[@]}"
+				do
+					if [[ "$scope" = "$value" ]]; then
+						scopeFound='yes'
+						break
+					fi
+				done
+
+				# error ir scope wasn't defined in config file
+				if [[ ! "$scopeFound" = "yes" ]]; then
+					display_error "Scope '$scope' is not a valid scope per configuration file '$config'." "$1" 1
+					exit 1
+				fi
+			fi
+
+		else
+			display_error "First line must not contain more than $firstLineLengthMax characters as defined in the configuration file '$config'." "$1" "$count"
+			exit 1
+		fi
+
+	else
+			display_error "First line must contain at least $firstLineLengthMin characters as defined in the configuration file '$config'." "$1" "$count"
+		exit 1
+	fi
+
+done < <(head -1 "$1")
+
+
+# eval lines 2 and after
+
+mode='title'
+count=2
+countBreakingChange=0
+
+while IFS= read -r line
+do
+
+	if [[ "$mode" = "title" ]]; then
+
+		if [ -z "$line" ]; then
+			# 2nd line is a newline
+			mode='body'
+		else
+			# 2nd line is present, and isn't a newline (e.g. empty line)
+			display_error "Second line, if present, must be empty." "$1" "$count"
+			exit 1
+		fi
+
+	elif [[ "$mode" = "body" ]]; then
+
+		# remain in this mode until EOF
+
+		if [ -n "$line" ]; then
+			#line isn't empty
+
+			# check that the line has at least min chars
+			if is_string_min_char_compliant "$line" "$bodyLineLengthMin"; then
+
+				# check that the tline doesn't exceed max chars
+				if is_string_max_char_compliant "$line" "$bodyLineLengthMax"; then
+
+					# the reformatting ensures this form, if present
+					regexp="BREAKING CHANGE: ([a-zA-Z])"
+
+					if [[ $line =~ $regexp ]]; then
+						(( "countBreakingChange++" ))
+					fi
+
+				else
+					display_error "Body line must not contain more than $bodyLineLengthMax characters as defined in the configuration file '$config'." "$1" "$count"
+					exit 1
+				fi
+			else
+				display_error "Body line must contain at least $bodyLineLengthMin characters as defined in the configuration file '$config'." "$1" "$count"
+				exit 1
+			fi
+		fi
+	fi
+
+
+	(( "count++" ))
+
+done < <(tail -n +2 "$1")
+
+
+if [ "$countBreakingChange" -gt 1 ]; then
+	display_error "Only one 'BREAKING CHANGE' statement allowed." "$1"
+	exit 1
+fi
+
+
+# note that not checking tokens in footer, and specifically that they contain a '-'
+
+
+display_error "Always error out for testing" "$1"
 exit 1
 
